### ISSUE TITLE
Add monitoring for MS ASR rules - Untrusted Binaries

### ISSUE THREAD

**Issue by 21gramaz** [bm9w/solid-pancake#6]
Extra Info:
Get-WinEvent -LogName "Microsoft-Windows-Windows Defender/Operational" | Where {($_.Id -eq "1121") -or ($_.Id -eq "1122")}
Block executable files from running unless they meet a prevalence, age, or trusted list criterion - 01443614-cd74-433a-b99e-2ecdc07bfc25

**Comment by mosajjal** [comment]
this is done in the latest commit :)
